import fs from 'node:fs';
import path from 'node:path';
import {renderBrand,registerEditorial,topicResearch,posts as basePosts} from './editorial.mjs';
import {referenceFor} from './reference-data.mjs';
import {homepage} from './homepage.mjs';
import {renderTenBrandGuide,expandedPosts} from './library.mjs';
import {readingTools,navigationUI} from './navigation.mjs';
const root=path.resolve(import.meta.dirname,'..'), out=path.join(root,'dist');
const indexNow=JSON.parse(fs.readFileSync(path.join(root,'data/indexnow.json'),'utf8'));fs.writeFileSync(path.join(out,indexNow.key+'.txt'),indexNow.key);
const origin='https://fanqiangdaohang.blog', date='2026-10-08';
const raw=[
['breezenet','微风网络 Breezenet','https://edp01.breezenetaff.com/#/?code=4KDOroY0','weifeng90','周期与不限时选择','不固定使用时长的用户','先比较按月流量与一次性流量的有效期，确认是否允许流量重置。',0],
['flycat','飞猫云','https://flycat1.flycatvipaff.cc/#/?code=Os3T3OxW','flycat888','小流量入门方案','轻量上网与备用需求','小包是否仅限年付、每月流量如何重置，比折算月价更值得先确认。',0],
['twilight','暮光网络','https://varnexa.twilightaff.com/#/?code=3qqonTlH','','定制方案选择','有特定地区线路需求的用户','询问定制节点的地区、独享范围与交付周期，避免将定制入口理解为默认套餐。',0],
['dalaocloud','大佬云','https://vip.dalaocloud.com/#/?code=Cp2sfYZg','','轻量套餐定位','优先控制总预算的用户','第三方资料的年付折算价与常规月价不同，购买前按实际付款周期核对。',3],
['firefly','Firefly机场','https://vip02.fireflyaff.com/#/?code=Fes6j9rn','firefly','专线线路定位','关注线路类型的用户','公开资料将其列为 IPLC 候选；线路名称不能替代你在本地网络的实际体验。',1],
['civet','灵猫','https://vip02.civetaff.com/#/?code=kZlRw46w','','多周期套餐选择','按使用周期安排预算的用户','比较相同流量档的月付、季付与年付总价，明确退款政策后再选择周期。',0],
['flashleap','闪跃 FlashLeap','https://vip02.flashleapaff.com/#/?code=FkCGEeaC','shanyue','IPLC 专线定位','需要比较专线服务的用户','确认当前套餐的节点倍率；宣传的线路类型与结算流量是两个不同的问题。',1],
['worryfree','无忧链接','https://wep01.worryfreeaff.com/#/?code=56A0RTpU','wuyou666','不限时流量选择','间歇使用与备用需求','一次性流量适合不固定用量，但仍需查看到期规则及账号保留政策。',0],
['kuajie','跨界云','https://vip02.kuajieaff.com/#/?code=VfWeYwHM','','大流量套餐选择','经常下载或观看视频的用户','先核对高流量档的节点倍率、并发限制和是否能在周期内重置。',0],
['stardream','星岛梦 StarDream','https://kfccbb.xingdaomeng.com/#/?code=JTRIWFim','nmw888','周期与流量包选择','需要灵活安排流量的用户','将月付和一次性方案分开比较；套餐跨度不直接说明实际速度与可用性。',0],
['lightspeed','光速云 LightSpeed','https://mdlky.gsyaff.com/#/?code=6tRWbtgK','jichangcha09','套餐层级较丰富','从轻量到高用量的用户','同一品牌不同套餐可能使用不同节点池，先看目标套餐能访问哪些节点。',0],
['v2yun','唯兔云（V2云）','https://fast.v2yunvipaff.com/#/?code=xYEe8gyb','rabbit','小包与不限时方案','希望同时比较两种计费方式的用户','两种别名对应本页同一入口，注册和续费请使用自己保存的账户信息。',0],
['u1s1','U1S1（有一说一）','https://pkdj7.vipaff.cc/#/?code=NMjmHbvu','U1S1','多档流量选择','用量会随月份变化的用户','确认升级套餐时剩余价值是否折抵，以及升级后原有流量如何处理。',0],
['jilian','极连云','https://kdjhao.jlyvipaff.com/#/?code=poyoU7mq','','轻量与定制方案','想从小套餐开始的用户','公开资料中的线路和协议描述存在差异，导入前核对当前订阅格式。',0],
['globalcloud','全球云','https://sswdh.gcvipaff.com/#/?code=NE1AcNIX','tt88','一次性流量包选择','需要按实际用量安排购买的用户','一次性包与月度包的流量计费可能不同，先读有效期与倍率说明。',0],
['guangnian','光年梯','https://ggmq.gntaff.com/#/?code=RAJFvngV','','轻量到高用量覆盖','准备逐步增加流量的用户','从低档开始观察一周用量，再估算整月需要多少流量。',0],
['sogo','Sogo云','https://wzjc.sogoyunaff.cc/#/?code=2x2EywO9','','专线定位','准备比较线路方案的用户','不同公开资料对协议的描述不一致，以当前客户端下载说明为准。',2],
['yuzhou','宇宙云 YuZhou','https://wzjc.yuzoucloud.cc/#/?code=wL7YStBa','YUZHOU553','小包与常规档并存','轻量使用后再升级的用户','比较首购优惠和续费价格；优惠后的首月成本不代表长期成本。',0],
['2mao','二猫云 2mao','https://waaa.2maoyunaff.cc/#/?code=uHeyKG44','','小流量套餐选择','流量需求较少的用户','年付小包与月付小包分别核对，不要把不同方案的价格和流量拼在一起。',0],
['1fly','一翻云 1fly','https://wzjc.1flyunaff.cc/#/?code=F7eaT191','','客户端与订阅兼容','希望使用现有客户端的用户','安装前确认软件系统版本要求，以及订阅是否适配你正在使用的客户端。',0],
['edgenova','边缘节点 EdgeNova','https://work.edgenovaaff.cc/#/?code=z81zCfw1','','多档用量方案','想控制入门成本的用户','自动分配线路是资料中的定位，是否适合本地运营商仍需实际观察。',0],
['kosing','可信云','https://work.kosingaff.com/#/?code=BNsA58Es','','IEPL / VLESS 定位','需要进一步核对线路的用户','可查资料尚不完整，先确认套餐、节点和售后政策；本页不据此判断稳定性。',4],
['sujie','速界 SuJie','https://work.speedworldaff.cc/#/?code=wSjLCpIf','','专线候选','以线路比较为优先的用户','专线入口不等于所有地区都走相同路径，询问目标地区和入口运营商。',2],
['kuaili','快狸 KuaiLi','https://work.kuailicloud.cc/#/?code=gVGJa0Mp','','定制线路定位','有特定办公线路需求的用户','定制需求应先确认带宽、地区和服务范围，并与常规订阅分别比较。',2],
['flyv','飞V','https://varnexa.flyvaff.com/#/?code=UoU2Izm5','','独享线路方案选择','有特定出口需求的用户','独享方案是另行购买还是套餐默认包含，应在下单前向服务商确认。',0],
['laddercloud','梯子云 LadderCloud','https://varnexa.ladderaff.com/#/?code=kuE4kqxo','','客户端与多周期方案','希望兼顾导入和计费灵活性的用户','确认官方软件是否支持你的设备，同时保留通用订阅作为替代导入方式。',0],
['wavenet','浪网 WaveNet','https://varnexa.wavenetaff.com/#/?code=oU77JXen','','商业与定制档选择','高用量或特定线路需求的用户','商业档名称不代表服务承诺，查看设备数、并发限制和工单支持范围。',0],
['lingdong','灵动云','https://varnexa.lingdongaff.com/#/?code=QcRK6OPG','','大流量与单次流量选择','想比较不同流量方案的用户','AI 服务的地区支持会变化，购买前用目标节点访问自己实际需要的服务。',0],
['invisible','隐形人','https://varnexa.invisibleaff.com/#/?code=JF4seZUy','','周期与定制方案选择','需要比较多层级套餐的用户','品牌名称不能证明匿名性；对隐私有要求时，应单独阅读隐私政策与日志说明。',0]
];
const sources=[['机场探 · 品牌资料目录','https://jichangtan.com/airports/'],['机场推荐 · 专线候选目录','https://jichang360.bid/dedicated/'],['COIO · 参数目录','https://www.coio.net/'],['机场决策室 · 大佬云资料','https://jichangtuijian.homes/iepl-airport/'],['机场实测室 · 对照资料','https://jichangtuijian.mom/compare/']];
sources.push(['站长提供的博客 · 价格流量对比','https://jichang-tuijian.org/compare']);
const brands=raw.map(([slug,name,url,coupon,advantage,audience,check,source],i)=>({rank:i+1,slug,name,url,coupon,advantage,audience,check,source:sources[source],evidence:'第三方资料所述，本站未实测',updated:date}));
for(const b of brands){b.reference=referenceFor(b.slug);if(b.reference){b.previousSource=b.source;b.audience=b.reference.audience;b.source=[b.reference.provenance==='owner'?'站长直接提供的价格与流量':'站长提供的旧博客 · 品牌资料',b.reference.sourceUrl];b.advantage=b.reference.provenance==='owner'?'130GB · ￥23套餐参考':b.reference.line+' · '+b.reference.position;b.evidence='站长提供的参考资料，非本站实测';if(b.reference.provenance==='owner')b.check='核对130GB、￥23套餐的付款周期、流量重置与有效期；线路和协议仍需补充。';}}
fs.writeFileSync(path.join(root,'data/brands.json'),JSON.stringify(brands,null,2));
const topics=[
['airport-recommendations','机场推荐','从需求出发，选对订阅。','机场推荐先看流量、付款周期和目标地区，再查看线路说明。这里按固定顺序整理 29 个品牌入口与资料，帮助你把宣传和可核对的条件分开。',[['先列出使用场景','网页浏览、视频观看和文件下载的流量需求差别很大。先回看设备近一个月的实际用量，写下主要设备、目标地区与常用服务。用这张需求清单筛选套餐，比先看排行榜更容易做出适合自己的选择。'],['比较同一种付款周期','年付折算月价不等于可以按月购买。比较时把实际支付金额、服务期和每月流量放在同一行；一次性流量包则另外比较有效期。'],['入口与资料分开看','品牌名称和官网按钮直达本站维护的品牌入口；详情页保留优惠码、资料出处及需要继续核对的事项。先看详情再决定是否注册，可以减少反复打开多个网站的时间。']]],
['airport-recommendations-2026','机场推荐 2026','今年选机场，要看哪些变化？','机场推荐 2026 专题汇总当前收录的品牌、优惠码与选购检查项，强调资料日期、套餐周期及实际使用场景。',[['先看信息是否仍然适用','2026 年的文章标题并不保证套餐内容刚刚更新。价格、域名和节点都可能变化；打开官方订单页后，重新核对币种、流量、周期和优惠适用条件。'],['AI 与流媒体按目标服务核对','某个节点可以访问一种服务，并不代表能访问所有服务。测试时记录具体网站、地区、设备和时段。服务方的地区政策与风控也会影响结果。'],['留下一份购买记录','保存订单总价、付款周期、套餐流量、节点说明和售后政策。后续续费时与原记录比较，比单看促销标题更容易发现变化。']]],
['stable-airports','稳定机场推荐','稳定，应该怎样判断？','稳定机场推荐指南：从晚高峰、丢包、节点切换与售后响应考察体验。本页不把线路宣传或品牌排名当作稳定性实测结果。',[['测试你真正使用的时段','在常用网络中选相同地区节点，分别观察工作时间和晚间体验。记录连接失败次数、页面加载和视频缓冲，而不是只记一次最高下载速度。'],['把本地网络因素考虑进去','Wi-Fi 信号、家庭带宽、运营商路径和客户端设置都可能影响体验。出现异常时先使用同一设备对照其他节点，再判断问题是否来自服务商。'],['售后也是持续使用的一部分','查看官方工单和维护通知的入口。实际遇到问题时，记录反馈时间与解决过程；这比没有证据的可用率百分比更有参考价值。']]],
['cheap-airports','便宜机场推荐','看总成本，也看有效流量。','便宜机场推荐指南：区分月付与年付折算，核对流量倍率、优惠码和续费条件，按实际用量比较成本。',[['先看需要付多少钱','年付总额除以十二只是平均成本，实际仍可能需要一次性付款。预算有限时，把首笔支出和每月平均成本分开考虑。'],['按自己能用完的流量比较','大流量套餐每 GB 的标价可能较低，但闲置流量不能替你节省支出。先估算自己一个月能用完多少，再比较符合用量的档位。若有倍率，确认计费流量如何扣除。'],['优惠码以结算结果为准','本站保留站长提供的 11 个优惠码，不推断折扣比例和有效期。输入后检查订单总价，确认适用套餐、新客限制、最低周期以及续费是否可用。']]],
['dedicated-airports','专线机场推荐','看清线路，再看体验。','专线机场推荐指南：理解 IPLC、IEPL 与中转线路的资料口径，核对节点倍率与目标地区，避免只凭名称选择。',[['线路名称只是起点','IPLC 和 IEPL 描述的是线路服务类型，不能单独证明你拿到的套餐质量。确认所选套餐的节点列表、入口、出口地区和计费规则，再安排短周期体验。'],['关注目标地区的路径','同一个品牌不同节点可能走不同路径。香港节点表现不能代替美国或日本节点的结果。比较时使用自己的运营商网络，并以实际目标地区为准。'],['本目录不做专线真实性认证','品牌详情里的专线定位来自注明出处的公开资料。本站没有运营商合同、线路账单或独立测试记录，因此不做“全专线”“永不拥堵”等承诺。']]],
['airport-ranking','机场排行榜','29 个品牌，一份清晰目录。','机场排行榜按站长指定顺序展示 29 个品牌，附核心优势资料、优惠码与品牌入口。顺序不代表独立测试分数。',[['这份榜单如何排序','本榜单严格按站长提供的品牌顺序排列，不使用价格、推广佣金或虚构测速分数重新排序。各专题及相关品牌区域同样保留这一顺序。'],['怎样使用榜单','先选择与你使用场景相符的品牌，再读详情页的来源和核对事项。排名可以帮助浏览目录，最终选择仍要看目标套餐、当前价格与自己的网络体验。'],['资料边界','本次整理日期为 2026 年 10 月 8 日。品牌入口和优惠码由站长提供；优势定位来自第三方公开资料。本站尚未完成这些品牌的独立测速，也未验证优惠码的结算效果。']]]
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const link=(url,label,external=false,cls='')=>`<a ${cls?`class="${cls}"`:''} href="${esc(url)}" ${external?'target="_blank" rel="sponsored nofollow noopener noreferrer"':''}>${esc(label)}</a>`;
const articleIndex=[...basePosts.map(p=>({route:'/blog/'+p[0]+'/',title:p[1],category:'选购基础',description:p[3]})),...expandedPosts({brands,esc:s=>String(s),link:(_,t)=>t}).map(p=>({route:'/blog/'+p.slug+'/',title:p.title,category:p.category,description:p.description}))];
fs.mkdirSync(path.join(out,'data'),{recursive:true});fs.writeFileSync(path.join(out,'data/articles.json'),JSON.stringify(articleIndex));
const routes=[];
const nav=`<a class="wordmark" href="/" aria-label="三毛机场首页"><span class="mark">S</span><span>三毛机场<small>品牌资料 · 选购研究</small></span></a><nav aria-label="主导航">${link('/#brands','品牌目录')}${link('/blog/','博客文章')}${link('/topics/','选购专题')}${link('/about/','编辑说明')}${link('/compare/','机场对比 →',false,'nav-compare')}</nav>`;
const footer=`<footer><div class="wrap footer-grid"><div><strong>三毛机场</strong><p>读懂套餐，找到适合你的连接。</p><small>© 2026 fanqiangdaohang.blog</small></div><div><h3>阅读专题</h3>${topics.map(t=>link('/guides/'+t[0]+'/',t[1])).join('')}</div><div><h3>探索内容</h3>${link('/blog/','机场博客')}${link('/topics/','专题中心')}${link('/compare/','机场对比')}${link('/about/','编辑说明与商业披露')}${link('/privacy/','隐私说明')}${link('/feedback/','资料更正与反馈')}${link('/data-status/','参数核对状态')}${link('/sitemap.xml','网站地图')}<p>入口含推广标识，本站可能获得佣金。<br>收录及排序不代表独立测速结论。</p></div></div></footer>`;
function page(route,title,description,keywords,body,extra=[],type='WebPage'){
body=readingTools(route,body,articleIndex);
const canonical=origin+route;
const schema=[{'@context':'https://schema.org','@type':type,name:title,url:canonical,description,inLanguage:'zh-CN',dateModified:date,publisher:{'@type':'Organization',name:'三毛机场',url:origin}},...extra];
if(type==='Article'){Object.assign(schema[0],{headline:title,author:{'@type':'Organization',name:'三毛机场编辑'},datePublished:date});}
const html=`<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="keywords" content="${esc(keywords)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="${canonical}"><meta property="og:type" content="${type==='Article'?'article':'website'}"><meta property="og:locale" content="zh_CN"><meta property="og:site_name" content="三毛机场"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${canonical}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(description)}"><meta name="theme-color" content="#0a172b"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/style.css?v=reading-8"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><script src="/assets/app.js?v=reading-8" defer></script></head><body id="top"><a href="#main" class="skip">跳到内容</a><header class="site-header"><div class="wrap header-inner">${nav}</div></header><main id="main">${body}</main>${footer}${navigationUI(body)}<div class="toast" role="status" aria-live="polite"></div></body></html>`;
const dest=route==='/'?'index.html':route.replace(/^\//,'')+'index.html';fs.mkdirSync(path.dirname(path.join(out,dest)),{recursive:true});fs.writeFileSync(path.join(out,dest),html);routes.push({route,title,description,keywords});
}
const crumb=(label,parent='/')=>`<div class="wrap breadcrumb">${link('/','首页')}<span>/</span>${parent!=='/'?link('/guides/airport-ranking/','机场排行榜')+'<span>/</span>':''}<span>${esc(label)}</span></div>`;
const breadcrumbSchema=(name,route)=>({'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'首页',item:origin+'/'},{'@type':'ListItem',position:2,name,item:origin+route}]});
const coupon=b=>b.coupon?`<button class="coupon" type="button" data-copy="${esc(b.coupon)}" aria-label="复制 ${esc(b.name)} 优惠码 ${esc(b.coupon)}"><span>优惠码</span><strong>${esc(b.coupon)}</strong><span>复制</span></button>`:'<span class="no-coupon">暂未提供优惠码</span>';
function card(b){return `<article class="brand-card" id="brand-${b.slug}" data-brand-search="${esc(b.name+' '+b.advantage+' '+(b.reference?.protocol||''))}" data-brand-category="${b.reference&&/专线|IPLC|IEPL/.test(b.reference.line)?'dedicated ':''}${b.reference&&/中转|隧道/.test(b.reference.line)?'relay ':''}${b.reference&&/年付|折算/.test(b.reference.priceBasis)?'annual':''}"><div class="card-top"><span class="rank">${String(b.rank).padStart(2,'0')}</span><span class="initial" aria-hidden="true">${esc(b.name.replace(/（.*?）/g,'').split(' ')[0].slice(0,2))}</span><span class="mini">品牌资料</span></div><h3>${link(b.url,b.name,true)}</h3><p class="advantage">${esc(b.advantage)}</p><p class="audience">适合关注：${esc(b.audience)}</p>${b.reference?`<dl class="card-parameters"><div><dt>参考价</dt><dd>${esc(b.reference.price)}</dd></div><div><dt>参考流量</dt><dd>${esc(b.reference.traffic)}</dd></div></dl>`:''}<span class="evidence">参考资料 · 非本站实测</span><div class="coupon-slot">${coupon(b)}</div><div class="card-actions">${link(b.url,'访问官网',true,'button primary')}${link('/brands/'+b.slug+'/','品牌详情',false,'button subtle')}</div></article>`;}
const directory=`<section class="wrap section" id="brands"><div class="section-heading"><div><span class="eyebrow">THE DIRECTORY / 29 BRANDS</span><h2>机场推荐品牌目录</h2></div><span class="muted">按站长指定顺序排列</span></div><div class="catalog-toolbar"><label class="catalog-search"><span>搜索品牌资料</span><input type="search" data-brand-query placeholder="品牌名称、线路或定位" autocomplete="off"></label><div class="catalog-filters" aria-label="品牌资料筛选"><button type="button" data-brand-filter="all" aria-pressed="true">全部</button><button type="button" data-brand-filter="dedicated" aria-pressed="false">专线资料</button><button type="button" data-brand-filter="relay" aria-pressed="false">中转资料</button><button type="button" data-brand-filter="annual" aria-pressed="false">年付参考</button></div><p data-brand-status role="status">29 个品牌 · 保持目录顺序</p></div><div class="brand-grid">${brands.map(card).join('')}</div><p class="catalog-empty" data-brand-empty hidden>没有匹配的品牌，可修改关键词或切换筛选。</p><p class="catalog-footnote">参考价格与流量未确认同一套餐，购买前请核对订单。品牌排序按站长指定顺序，不代表性能评分。</p></section>`;
const listSchema={'@context':'https://schema.org','@type':'ItemList',name:'机场推荐品牌目录',itemListOrder:'https://schema.org/ItemListOrderAscending',numberOfItems:29,itemListElement:brands.map(b=>({'@type':'ListItem',position:b.rank,url:origin+'/brands/'+b.slug+'/',name:b.name}))};
page('/','机场推荐 2026｜稳定、便宜与专线机场排行榜 - 三毛机场','机场推荐 2026：按固定顺序整理 29 个机场品牌、公开资料中的核心优势、11 个优惠码和品牌入口，附稳定机场推荐、便宜机场推荐及专线选购指南。','机场推荐,机场推荐 2026,稳定机场推荐,便宜机场推荐,专线机场推荐,机场排行榜',homepage({brands,topics,link,esc,directory}),[listSchema,{'@context':'https://schema.org','@type':'WebSite',name:'三毛机场',url:origin+'/',inLanguage:'zh-CN'}]);
for(const t of topics)renderTenBrandGuide(t,{page,crumb,breadcrumbSchema,link,esc,brands});
const editorialContext={page,crumb,breadcrumbSchema,link,coupon,topics,brands,card,esc};
for(const b of brands)renderBrand(b,editorialContext);
registerEditorial(editorialContext);
page('/about/','关于本站｜编辑说明与商业披露 - 三毛机场','了解三毛机场的资料来源、固定排名、推广链接及信息核对范围。','三毛机场,商业披露',`${crumb('编辑说明')}<article class="wrap prose standalone"><h1>编辑说明与商业披露</h1><h2>我们整理什么</h2><p>三毛机场整理 29 个品牌的入口、站长提供的优惠码和公开资料中的特点，帮助读者比较套餐与使用需求。本站不运营网络订阅服务。</p><h2>排名与来源</h2><p>所有品牌严格按站长提供的顺序展示。顺序不代表速度、价格、稳定性或安全性评分。每个品牌详情页标出第三方资料来源；本站尚未独立测速、登录品牌后台或验证优惠码。</p><h2>商业关系</h2><p>品牌入口含推广或邀请标识。用户经由这些入口注册或购买时，本站可能获得佣金。链接使用 sponsored 和 nofollow 标记。品牌的收费、退款及服务由相应服务商处理。</p><h2>资料日期与更新</h2><p>大佬云的参考套餐由站长直接补充：130GB、￥23，付款和流量周期待确认，线路与协议尚未补充。其余28个品牌参数来自站长提供的旧博客。本次资料整理日期为 2026 年 10 月 8 日，不等于全部套餐在当日经官方验证。价格、线路、优惠政策与品牌域名可能变化，请在付款前重新核对。</p><h2>资料出处</h2><ul>${sources.map(s=>`<li>${link(s[1],s[0],true)}</li>`).join('')}</ul></article>`);
page('/feedback/','资料更正与反馈 - 三毛机场','反馈品牌价格、流量、付款周期、优惠或链接错误，生成可核对的公开资料更正草稿。','资料更正,三毛机场反馈',`${crumb('资料更正')}<article class="wrap prose standalone"><h1>资料更正与反馈</h1><p>发现价格、流量、周期或链接变化？请填写对应页面与公开依据。本站生成反馈草稿，你可以复制保存，或到GitHub核对后提交（需要GitHub账号）。</p><p class="muted">这里只生成草稿，不会自动发送。请只填写公开资料，不填写账号、订阅密钥或付款信息。</p><form class="correction-form" data-correction-form><label for="feedback-page">需要更正的页面</label><input id="feedback-page" name="page" type="url" required maxlength="300" placeholder="https://fanqiangdaohang.blog/brands/…"><label for="feedback-type">更正类型</label><select id="feedback-type" name="type"><option>价格或付款周期</option><option>流量或重置方式</option><option>品牌入口失效</option><option>优惠条件</option><option>文章内容</option></select><label for="feedback-details">具体变化与公开资料出处</label><textarea id="feedback-details" name="details" required minlength="10" maxlength="1200" placeholder="例如：页面写……，当前公开套餐页写……，资料链接是……"></textarea><div class="correction-actions"><button type="submit" class="button primary">生成反馈草稿</button><button type="button" class="button subtle" data-correction-copy>复制反馈文字</button><a class="button primary" data-correction-link href="https://github.com/ksugiono187/fanqiangdaohang.blog/issues/new" target="_blank" rel="noopener noreferrer" hidden>到GitHub核对并提交</a></div><p data-correction-status role="status"></p></form><p>${link('/data-status/','查看资料核对状态')}</p></article>`);
page('/data-status/','品牌参数核对状态｜周期与资料缺口 - 三毛机场','查看29品牌价格、流量周期和资料核对状态。飞猫来源已补齐每月150GB，未确定的周期和套餐配对继续明确标注。','品牌参数,套餐周期,资料核对',`${crumb('资料核对状态')}<article class="wrap prose standalone"><h1>品牌参数核对状态</h1><p>2026年10月8日复核。飞猫旧博客品牌页明确描述每月150GB，已补齐这一来源口径。其他缺失周期未获得充分公开依据，继续保留待确认；访问入口成功不等于已验证套餐。</p><div class="source-note">下表是资料状态，不是品牌性能评级。旧博客起步价与流量未确认同档；大佬云130GB、￥23由站长直接补充，周期待确认。</div><div class="table-scroll" tabindex="0"><table class="audit-table"><thead><tr><th>品牌</th><th>参考价与口径</th><th>流量与周期</th></tr></thead><tbody>${brands.map(b=>`<tr><th scope="row">${link('/brands/'+b.slug+'/',b.name)}</th><td>${esc(b.reference.price)}<br>${esc(b.reference.priceBasis)}</td><td>${esc(b.reference.traffic)}<br>${esc(b.reference.trafficCycle)}</td></tr>`).join('')}</tbody></table></div><h2>怎样补齐待确认字段</h2><p>请提供当前公开套餐名称、服务期、实际总额、流量重置方式及资料出处。只有字段对应同一档位时才进入套餐成本比较。${link('/feedback/','提交资料更正草稿')}</p></article>`);
page('/privacy/','隐私说明 - 三毛机场','三毛机场隐私说明：静态页面、优惠码复制及第三方品牌链接。','隐私说明',`${crumb('隐私说明')}<article class="wrap prose standalone"><h1>隐私说明</h1><p>本站页面不要求注册，不提供评论、付款或账户管理，也未主动嵌入第三方统计或广告追踪代码。</p><h2>收藏、最近阅读与进度</h2><p>阅读记录保存在当前浏览器的本地存储中，包括页面地址、标题、收藏状态和最近阅读进度，最多保留100项收藏和20项最近阅读。不上传到服务器，不跨设备同步。你可以在“我的阅读”中取消收藏或清空最近记录，也可以通过浏览器设置清除全部站点数据。浏览器禁止本地保存时，仅在当前页面内保留临时状态。</p><h2>资料反馈</h2><p>反馈表只生成草稿或复制文字，不自动向本站发送。选择GitHub提交时，将进入该平台，由你核对草稿并提交，按GitHub账户与隐私规则处理。</p><h2>优惠码复制</h2><p>点击复制按钮时，页面尝试把所选优惠码写入你的剪贴板。若浏览器不支持复制，页面会显示提示，方便你手动复制。</p><h2>品牌网站</h2><p>品牌入口包含推广标识，点击后进入相应第三方网站，其数据收集、注册和付款遵循该网站的政策。本站不接收你在第三方填写的密码或付款信息。</p><h2>托管访问记录</h2><p>网站托管服务可能为运行、维护和安全记录请求日志，包括 IP 地址、访问时间和浏览器信息。具体处理方式取决于最终托管提供商；上线配置发生变化时应更新本说明。</p><p>最后更新：2026 年 10 月 8 日。</p></article>`);
fs.mkdirSync(path.join(out,'assets'),{recursive:true});
fs.writeFileSync(path.join(out,'favicon.svg'),'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#0a172b"/><text x="32" y="46" text-anchor="middle" font-family="Georgia,serif" font-size="46" font-weight="bold" fill="#88ecd0">S</text></svg>');
fs.writeFileSync(path.join(out,'robots.txt'),`User-agent: *\nAllow: /\n\nSitemap: ${origin}/sitemap.xml\n`);
fs.writeFileSync(path.join(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routes.map(r=>`<url><loc>${origin}${r.route}</loc><lastmod>${date}</lastmod></url>`).join('')+'</urlset>');
fs.writeFileSync(path.join(root,'data/seo.json'),JSON.stringify(routes,null,2));
fs.writeFileSync(path.join(out,'404.html'),`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>页面未找到 - 三毛机场</title><link rel="stylesheet" href="/assets/style.css?v=reading-8"><main class="wrap prose standalone"><h1>页面未找到</h1><p>这个地址暂时没有内容。</p><a class="button primary" href="/">回到首页</a></main></html>`);
console.log(`Built ${routes.length} indexable pages and 29 brand profiles.`);
