export function registerBuyingTools({brands,page,crumb,link,esc}){
 const links=`<div class="buying-shortcuts">${[['/plans/','套餐资料表'],['/finder/','选购筛选'],['/updates/','更新记录'],['/usage-records/','我的使用记录']].map(([u,t])=>link(u,t,false,'button subtle')).join('')}</div>`;
 const wrap=(name,body)=>`${crumb(name)}<article class="wrap prose standalone"><h1>${name}</h1>${links}${body}</article>`;
 const rows=brands.map(b=>({...b.reference,slug:b.slug,name:b.name}));
 page('/plans/','29品牌套餐资料表｜价格周期与流量核对 - 三毛机场','集中查看29品牌参考价格、付款口径、流量周期、套餐配对、倍率及设备限制，并进入品牌详情核对来源。','机场套餐,机场价格,机场对比',wrap('套餐资料表',`<p>这张表把现有资料放在同一处。除大佬云由站长提供价格与流量配对，其余记录仍是品牌级参考，未确认同一套餐。套餐名称、倍率与设备限制未取得可核对资料。</p><div class="table-scroll"><table class="plan-table"><caption>29品牌参考资料 · 2026年10月8日整理</caption><thead><tr><th>品牌 / 套餐名称</th><th>价格与付款口径</th><th>流量与周期</th><th>配对状态</th><th>倍率 / 设备限制</th><th>来源</th></tr></thead><tbody>${brands.map(b=>{const r=b.reference;return `<tr><th scope="row">${link('/brands/'+b.slug+'/',b.name)}<small>套餐名称待确认</small></th><td>${esc(r.price)}<small>${esc(r.priceBasis)}</small></td><td>${esc(r.traffic)}<small>${esc(r.trafficCycle)}</small></td><td>${r.provenance==='owner'?'站长提供价格与流量配对；周期待确认':'未确认同一套餐'}</td><td>待确认 / 待确认</td><td>${link(r.sourceUrl,r.provenance==='owner'?'站长提供':'原始资料',!r.sourceUrl.startsWith('/'))}<small>资料读取 ${r.retrieved}</small></td></tr>`;}).join('')}</tbody></table></div><h2>购买前补齐这五项</h2><p>套餐名称、实际支付总额与服务期、流量重置日、各节点倍率、同时在线设备限制。保存订单页中的同一套餐资料后，才适合计算单位流量成本。年付折算价只表示月均预算，不能代表可以按月付款。</p>${link('/feedback/','提供公开套餐资料 →')}`));
 page('/finder/','机场选购筛选器｜预算与月度流量 - 三毛机场','按参考月均预算和每月流量筛选29个品牌，区分符合已知条件的候选、待确认资料和不符合条件的记录。','机场选购,便宜机场推荐,机场筛选',wrap('选购筛选器',`<p>从预算与用量缩小阅读范围。筛选依据是品牌级参考资料，不保证对应同一可购买套餐；年付折算价格也计入月均预算。所有结果保留原始品牌顺序。</p><form class="buying-form" data-finder><label>月均参考预算<select name="budget"><option value="0">不限</option><option value="10">10元以内</option><option value="20">20元以内</option><option value="30">30元以内</option></select></label><label>每月流量需求<select name="traffic"><option value="0">不限</option><option value="50">至少50GB</option><option value="100">至少100GB</option><option value="150">至少150GB</option></select></label><label>同时在线设备<select name="devices"><option value="0">暂不筛选</option><option value="2">至少2台</option><option value="4">至少4台</option></select></label><button type="reset" class="button subtle">重置条件</button></form><p data-finder-status role="status"></p><div data-finder-results>${brands.map(b=>`<p>${link('/brands/'+b.slug+'/',b.name)} · ${esc(b.reference.price)} · ${esc(b.reference.traffic)}</p>`).join('')}</div><noscript><p>启用JavaScript后可筛选；上方仍可浏览全部品牌。</p></noscript><p>设备限制目前全部待确认。选择设备数量后，不能把缺资料的品牌视为满足条件。流量未知周期的记录同样列入待确认。</p><script type="application/json" id="finder-data">${JSON.stringify(rows).replace(/</g,'\\u003c')}</script>`));
 page('/updates/','网站更新记录｜价格资料与编辑变化 - 三毛机场','查看三毛机场已完成的价格补充、流量周期更正、内容与选购工具更新，区分资料整理和官方验证。','机场资料更新,套餐变更',wrap('更新记录',`<p>这里记录实际完成的编辑变更。资料读取日期不等于服务商价格更新日期，也不代表优惠码已在结算中验证。</p><section class="update-entry"><time datetime="2026-10-08">2026年10月8日</time><h2>增加选购工具与资料透明度</h2><p>新增29品牌套餐资料表、按参考预算与月度用量筛选、更新记录及本机使用记录。套餐名称、倍率与设备限制继续标为待确认。</p></section><section class="update-entry"><time datetime="2026-10-08">2026年10月8日</time><h2>飞猫流量周期补充</h2><p>此前150GB的流量周期未明确。重新读取来源品牌页后，补为“来源品牌页明确每月150GB”。仍未确认其与年付折算参考价对应同一套餐。</p>${link('https://jichang-tuijian.org/brands/flycat','查看来源品牌页',true)}</section><section class="update-entry"><time datetime="2026-10-08">2026年10月8日</time><h2>大佬云价格与流量补充</h2><p>根据站长直接提供的信息补入130GB、￥23。未提供付款和流量周期，未写作月付套餐。</p>${link('/brands/dalaocloud/','查看大佬云详情')}</section><section class="update-entry"><time datetime="2026-10-08">2026年10月8日</time><h2>内容与阅读功能扩充</h2><p>增加150篇选购研究文章，完善六个十品牌专题；增加全文目录搜索、收藏、最近阅读、文章目录与资料更正入口。</p></section><p>${link('/data-status/','查看尚待确认的资料 →')}</p>`));
 page('/usage-records/','我的使用记录｜设备网络与节点观察 - 三毛机场','在自己的浏览器记录品牌、设备、运营商、节点、日期与使用结果，导出记录便于按相同条件比较。','机场使用记录,网络体验记录',wrap('我的使用记录',`<p>填写你实际观察到的结果，按同一设备、运营商与地区比较不同时间的体验。记录只保存在本浏览器，不公开、不上传；本站目前没有独立实测数据。</p><form class="buying-form" data-usage-form><label>品牌<select name="brand">${brands.map(b=>`<option value="${b.slug}">${esc(b.name)}</option>`).join('')}</select></label><label>观察日期与时间<input name="date" type="datetime-local" required></label><label>设备与客户端<input name="device" required maxlength="100" placeholder="例如 Windows电脑 / 客户端版本"></label><label>运营商与接入网络<input name="network" required maxlength="100" placeholder="例如 电信 / 家庭Wi-Fi"></label><label>节点地区与名称<input name="node" required maxlength="100" placeholder="只填公开名称，不填订阅链接"></label><label>观察结果<textarea name="result" required maxlength="1000" placeholder="具体网站、持续时间、连接失败或缓冲情况；测速填写单位和方法"></textarea></label><button type="submit" class="button primary">保存到本浏览器</button><button type="button" data-usage-export class="button subtle">导出记录</button></form><p data-usage-status role="status"></p><div data-usage-list></div><h2>怎样形成有参考价值的记录</h2><p>每次记录明确测试方法、时间和目标地区。下载速率写清Mbps或MB/s，延迟写清目标与毫秒；一次测速不能证明长期稳定性。结果属于你当时的使用环境，不作为全体用户体验结论。请勿保存账号、密钥或订阅地址。</p>`));
}
